version: '3'

services:

  top_pages_monolith_backend_mongo_db:
    image: mongo
    restart: 'no'
    volumes:
      - "./mongo-db/init.js:/docker-entrypoint-initdb.d/init.js:ro"
      - "./mongo-db/data:/data/db"
    environment:
      MONGO_INITDB_ROOT_USERNAME: 'top_pages_root'
      MONGO_INITDB_ROOT_PASSWORD: 'top_pages_root_pass'
    ports:
      - 27017:27017

  mongo_express:
    image: mongo-express
    restart: 'always'
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: 'top_pages_root'
      ME_CONFIG_MONGODB_ADMINPASSWORD: 'top_pages_root_pass'
      ME_CONFIG_MONGODB_SERVER: 'top_pages_monolith_backend_mongo_db'
    depends_on:
      - top_pages_monolith_backend_mongo_db
